### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ospfranco** [sergeymild/react-native-jsi-cpr#1]
Hi @sergeymild, have you benchmarked the package? Do you know how much faster that RN default `fetch` implementation is this?

**Comment by sergeymild** [comment]
Hi, no i don't have any benchmarks, but i will think about this, and how to benchmark it.

**Comment by sergeymild** [comment]
@ospfranco i will answer with your words))

This will be heavily dependent on how much data you transfer. The more data you fetch in one go the more you will benefit from the JSI bindings.

If you are willing to create a test suite yourself, then I will gladly merge the PR.))
The benefit of the JSI is very clear when transmitting large amounts of data between the native side and JS. How much will depend on each application. Therefore I'm not keen in posting metrics. Just rest assured, it's faster than the old implementation

And one word from me. I like `react-native-jsi-cpr` more that `axios` or `fetch` first of all it more easy and convenient to use. it has more clear api and no throw exceptions only response with error or success type.
Easiest way to cancel request or catch either local or server timeout with different type of http error code.

**Comment by ospfranco** [comment]
I discussed shortly with @Szymon20000 and we weren't so sure. Apple's implementation of XML HTTP request are already faster than any other implementation I think. But fair enough, I will give it a go later and see for myself.

**Comment by sergeymild** [comment]
@ospfranco Yes you absolutely right, that native IOS URLSession works little bit faster that any of other implementations, but not dramatically and if we are a talking about Android's OkHttp, then curl will be faster but again not dramatically faster. as i told you before for me `react-native-jsi-cpr` is more convenient to use. I using it in my few production projects and do not have any problems with it

**Comment by sergeymild** [comment]
my first version of this library was a simple jsi wrapper on top of IOS URLSession and Android OkHttp, but later i decided to move everything to c++ and see what comes from it)

**Comment by JoshW219** [comment]
@ospfranco @sergeymild would be very cool if you guys could post your findings.

**Comment by ospfranco** [comment]
Haven't tried, just create a sample rn project and use console.time, it's not that hard

**Comment by ospfranco** [comment]
Created a sample repo with a basic request:

https://github.com/ospfranco/jsi-cpr-test

Android

fetch:
293ms
cpr:
112ms

iOS

fetch:
154ms
cpr:
148ms

- On android there is a big big difference, whereas on iOS it's minimal
- Fetch implements caching, so sub-sequent requests are faster on fetch
- Not related but on android it seems the package downloads another boost version? it just makes installing the library really slow
- on iOS I couldn't get it to compile for simulator, had to run on device
- I didn't really bother too much with release/debug flags, the behavior might be different once compiled for release. Unfortunately don't have time for further testing, so if somebody can take the repo and produce release versions and measure, that would be great

**Comment by ospfranco** [comment]
So following some suggestions on twitter I did further testing:
- Added axios
- Turned on Fabric

![IMG_4040](https://user-images.githubusercontent.com/1634213/186824037-c3a7dc0e-6cc7-4183-8116-e3fa5a5666ff.PNG)
![Screenshot_20220826-064427](https://user-images.githubusercontent.com/1634213/186824046-8a4cb0f8-9bde-403c-a847-ca70b6739c5c.png)

Results
- Axios seems to be consistently faster than either fetch or jsi-cpr either on Android or on iOS (bummer)
- This library is not compiling on Android with fabric enabled (got an error on the cmakelists file)

So I guess it is better to stick with Axios. If you notice I have done anything wrong during testing let me know (the repo is updated)

**Comment by ospfranco** [comment]
The folks at twitter have helped me and pointed out that axios also uses RCTNetworking underneath, so doing a fetch request before doing the axios one will actually cache the response, it seems that both Axios/Fetch have somewhat similar performance. So I guess jsi-cpr is indeed a bit faster (with the exception of cached requests). All very interesting stuff.

**Comment by vaidyakhil** [comment]
@sergeymild thanks for this repository, helped me in understanding the concept better!
@ospfranco  thanks for this issue.

At work we were trying out a similar idea to use JSI for network layer.
The idea is pretty much the same as this repository but using `URLSession` on iOS and `OkHttp` on Android for doing the request.

To benchmark:
-  I have mocked the response for an API using [Charles proxy](https://www.charlesproxy.com/) to avoid any variance due to network.
- The request is repeated 600 times using each module and the response is not cached for any of them (can verify this with charles)
- React-Native: `0.72.5` (because that is where we are at in production)
- New Arch - Disabled

Posting the results for `iOS`, The results did not make much sense to me and **my intention to post these is, if anyone of you can make sense of these and shed some light**.

![IMG_0103](https://github.com/sergeymild/react-native-jsi-cpr/assets/28788363/63440624-2f87-495c-9694-0d91e3b1ed55)

**Comment by ospfranco** [comment]
caching I would guess.

Without looking at your code and understanding how the native code behaves, there is no way of telling.

**Comment by vaidyakhil** [comment]
Thanks @ospfranco for the quick revert,
caching is not involved as I can see requests being called out on Charles.

Posting relevant code snippets

### JS Layer
```
    const Skynet: NetworkModule = {
      sendRequest: async () => {
        return new Promise((resolve, reject) => {
          skynet_rn_jsi_sendRequest(
            {
              skynet_rn_jsi_uniqueId: `skynet_rn_jsi_sendRequest_${Date.now()}`,
            },
            (responseData, errorData) => {
              if (responseData) {
                // do some data massaging before returning
                resolve(responseData);
              } else {
                // if want to never reject, resolve here as well with helpful error data
                reject(errorData);
              }
            },
          );
        });
      },
    };    

    const cprHttpClient = new JsiHttp({
      baseUrl: 'https://metrics.cocoapods.org',
      timeout: 1000,
    }, __DEV__)

    function delay(time) {
      return new Promise(resolve => setTimeout(resolve, time));
    }

    const makeNetworkCallViaJSI = async () => {
      return await Skynet.sendRequest();
    }
  
    const makeNetworkCallViaCPR = async () => {
      return await cprHttpClient.get('api/v1/pods/CocoaAsyncSocket');
    }
  
    const makeNetworkCallViaFetch = async () => {
      return await fetch('https://metrics.cocoapods.org/api/v1/pods/CocoaAsyncSocket');
    }

  const getFunctionWithMeasures = (originalApi: Function) => {
    return async (...args) => {
      const start = Date.now();
      const originalResponse = await originalApi(...args);
      const end = Date.now();
      const diff = end - start;

      if (__DEV__) {
        console.info(`${originalApi.typeOfCommLayer}: ${diff}ms | response type: ${typeof originalResponse}`);
      }

      return {
        response: originalResponse,
        measure: {
          timeTaken: diff
        }
      }
    }
  }

  React.useEffect(() => {

    const runExperiment = async () => {
      const jsiButtonClick = async () => {
        makeNetworkCallViaJSI.typeOfCommLayer = 'jsi';
        const callApi = getFunctionWithMeasures(makeNetworkCallViaJSI);
  
        const wrappedResponse = await callApi()
        appendResponse({ type: 'jsi', roundTrip: wrappedResponse.measure.timeTaken })
      }
  
      const cprButtonClick = async () => {
        makeNetworkCallViaCPR.typeOfCommLayer = 'cpr';
        const callApi = getFunctionWithMeasures(makeNetworkCallViaCPR);
  
        const wrappedResponse = await callApi()
        appendResponse({ type: 'cpr', roundTrip: wrappedResponse.measure.timeTaken })
      }
  
      const bridgeButtonClick = async () => {
        makeNetworkCallViaFetch.typeOfCommLayer = 'bridge';
        const callApi = getFunctionWithMeasures(makeNetworkCallViaFetch);
  
        const wrappedResponse = await callApi()
        appendResponse({ type: 'bridge', roundTrip: wrappedResponse.measure.timeTaken })
      }

      const moduleCallMap = {
        jsi: jsiButtonClick,
        cpr: cprButtonClick,
        bridge: bridgeButtonClick
      };

      await delay(500);

      for (let idx = 0; idx < MODULE_TYPES.length; idx++) {
          moduleUnderExperiment.current = MODULE_TYPES[idx];
          let iter = 0;
          while(iter < 600) {
            await moduleCallMap[MODULE_TYPES[idx]]();
            await delay(200);
            iter++;
          }
      }
    }

    runExperiment();
  }, [])
```

---


### C++ Bindings
``` 
void sendToJS(Runtime &runtime, std::string uniqueId,
              NSDictionary *responseDictionary) {
  global_jsCallInvoker->invokeAsync([=, &runtime]() {
    facebook::jsi::Object responseObject =
        convertNSDictionaryToJSIObject(runtime, responseDictionary);
    auto jsCallback = global_callbacks[uniqueId];

    // handling only success case
    jsCallback->call(runtime, responseObject, facebook::jsi::Value::undefined());
    global_callbacks.erase(uniqueId);
  });
}

void doRequest(Runtime &runtime, NetworkModule *networkModule,
               std::string uniqueId) {

  void (^networkModuleCompletionCallback)(
      NSData *_Nullable, NSURLResponse *_Nullable, NSError *_Nullable) =
      ^(NSData *_Nullable data, NSURLResponse *_Nullable response,
        NSError *_Nullable error) {
        if (error) {
          NSLog(@"Error: %@", error);
          return;
        }

        if (!data) {
          NSLog(@"No data");
          return;
        }

        // got response
        NSLog(LOG_ID, @"got response");
        NSDictionary *responseDictionary = [NSJSONSerialization
            JSONObjectWithData:data
                       options:NSJSONReadingMutableContainers
                         error:nil];

        // calling sendToJS
        NSLog(LOG_ID, @"calling sendToJS");
        sendToJS(runtime, uniqueId, responseDictionary);
      };

  // networkModule makeRequest
  NSLog(LOG_ID, @"networkModule makeRequest");
  [networkModule makeRequest:networkModuleCompletionCallback];
}

void installSendRequest(facebook::jsi::Runtime &jsiRuntime,
                        NetworkModule *networkModule) {
  NSLog(LOG_ID, @"installSendRequest");

  facebook::jsi::Function sendRequest = Function::createFromHostFunction(
      jsiRuntime, PropNameID::forAscii(jsiRuntime, SEND_REQUEST_METHOD_ID), 0,
      [networkModule](Runtime &runtime, const Value &thisValue,
                      const Value *arguments, size_t count) -> Value {
        // store callback for request
        NSLog(LOG_ID, @"store callback for request");
        auto requestObject = arguments[0].asObject(runtime);
        std::string uniqueId =
            requestObject.getProperty(runtime, REQUEST_ID_KEY.c_str())
                .asString(runtime)
                .utf8(runtime);
        auto jsCallback = arguments[1].getObject(runtime).asFunction(runtime);
        global_callbacks[uniqueId] =
            std::make_shared<facebook::jsi::Function>(std::move(jsCallback));

        NSLog(LOG_ID, @"call doRequest");
        // Note: this networkModule is using URLSession
        doRequest(runtime, networkModule, uniqueId);

        return Value();
      });

  jsiRuntime.global().setProperty(
      jsiRuntime,
      facebook::jsi::String::createFromUtf8(jsiRuntime, SEND_REQUEST_METHOD_ID),
      std::move(sendRequest));
}
```

**Comment by ospfranco** [comment]
No, I mean URLSession already has caching backed in

**Comment by ospfranco** [comment]
In any case, after more testing I decided to abandon this path. The performance benefit is minimal all things considered and you have a complete custom stack for network requests which on the long term was not worth it for me.

Going to unsubscribe from this thread. Good luck!
